- name: Install packages from repository
  dnf:
    name:  "{{item}}"
    state: latest
  with_items:
    - htop
    - vim-enhanced
    - python2-libselinux
    - zsh
- name: Install antibody
  shell: curl -sL git.io/antibody | sh -s warn=False
  args:
    creates: /usr/local/bin/antibody
- name: Autoremove packages
  dnf:
    autoremove: yes

