- name: Fedora version
  command: rpm -E '%fedora'
  register: fedora_version
- name: Install packages from repository
  dnf:
    name:  "{{item}}"
    state: latest
  with_items:
    - htop
    - vim-enhanced
    - python2-libselinux
    - fish
    - golang-bin
    - krita
    - https://downloads.vivaldi.com/stable/vivaldi-stable-2.0.1309.37-2.x86_64.rpm
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{fedora_version.stdout}}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{fedora_version.stdout}}.noarch.rpm
- name: Remove unwanted packages
  dnf:
    name: "{{item}}"
    state: absent
  with_items:
    - zsh
- name: Autoremove packages
  dnf:
    autoremove: yes
- name: copy VS Code settings file
  copy: src=files/settings.json dest=/home/stuart/.config/Code/User/settings.json owner=stuart group=stuart mode=0640

