- name: Install packages from repository
  dnf:
    name:  "{{item}}"
    state: latest
  with_items:
    - htop
    - vim-enhanced
    - python2-libselinux
    - fish
- name: Remove unwanted packages
  dnf:
    name: "{{item}}"
    state: absent
  with_items:
    - zsh
- name: Autoremove packages
  dnf:
    autoremove: yes

