- hosts: localhost
  become: true
  tasks:
    - include: tasks/hostname.yml
    - include: tasks/packages.yml
    - include: tasks/auto-ansible.yml
    - name: Add zsh to stuart user
      user:
        name: stuart
        shell: /bin/zsh
        password: $6$zxB5xUurvxljVcFv$ar2HDfGnGhozDVz/eHSsS5KjqUhViI3xVs6kyfuPUaPTQp.YWZ9Cg3ERLSm3b2w0mLu8cglEaqJNpDjxY1vqK1
        home: /home/stuart
    - include: tasks/zsh.yml

