- hosts: localhost
  become: true
  tasks:
    - include: tasks/hostname.yml
    - include: tasks/packages.yml
    - include: tasks/auto-ansible.yml
    - name: Add fish to stuart user
      user:
        name: stuart
        shell: /bin/fish
        password: $6$zxB5xUurvxljVcFv$ar2HDfGnGhozDVz/eHSsS5KjqUhViI3xVs6kyfuPUaPTQp.YWZ9Cg3ERLSm3b2w0mLu8cglEaqJNpDjxY1vqK1
        home: /home/stuart
    - name: Install fish_prompt
      copy: src=files/fish_prompt.fish dest=/home/stuart/.config/fish/functions/fish_prompt.fish owner=stuart group=stuart mode=0700
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: stuart
          visual_studio_code_extensions:
            - ms-vscode.go
            - kelvin.vscode-sshfs
            - vscoss.vscode-ansible
            - lunaryorn.fish-ide

